// Built-in extended medicine names trained from user-provided list (exact match only)
// Source: attachments provided by user (medicines.txt)

export const EXTENDED_MEDICINE_NAMES: string[] = [
  'Paracetamol',
  'Calpol',
  'Dolo 650',
  'Crocin',
  'Combiflam',
  'Ibuprofen',
  'Brufen',
  'Ibugesic',
  'Naproxen',
  'Diclofenac',
  'Voltaren',
  'Etoricoxib',
  'Meloxicam',
  'Indomethacin',
  'Aspirin',
  'Acetylsalicylic acid',
  'Tramadol',
  'Tapentadol',
  'Codeine',
  'Pantoprazole',
  'Pantop',
  'Protonix',
  'Omeprazole',
  'Losec',
  'Esomeprazole',
  'Nexium',
  'Lansoprazole',
  'Rabeprazole',
  'Ranitidine',
  'Famotidine',
  'Domperidone',
  'Metoclopramide',
  'Ondansetron',
  'Granisetron',
  'Promethazine',
  'Domstal',
  'Metformin',
  'Glucophage',
  'Glibenclamide',
  'Gliclazide',
  'Glimepiride',
  'Sitagliptin',
  'Saxagliptin',
  'Vildagliptin',
  'Dapagliflozin',
  'Canagliflozin',
  'Empagliflozin',
  'Insulin (Human)',
  'Insulin Glargine',
  'Insulin Aspart',
  'Insulin Lispro',
  'Atorvastatin',
  'Rosuvastatin',
  'Simvastatin',
  'Pravastatin',
  'Fenofibrate',
  'Bezafibrate',
  'Ezetimibe',
  'Amlodipine',
  'Losartan',
  'Telmisartan',
  'Valsartan',
  'Olmesartan',
  'Enalapril',
  'Ramipril',
  'Perindopril',
  'MetoProlol',
  'Atenolol',
  'Bisoprolol',
  'Carvedilol',
  'Nebivolol',
  'Clopidogrel',
  'Prasugrel',
  'Ticagrelor',
  'Warfarin',
  'Rivaroxaban',
  'Apixaban',
  'Dabigatran',
  'Amoxicillin',
  'Augmentin',
  'Amoxicillin-Clavulanate',
  'Cefixime',
  'Cefuroxime',
  'Cefalexin',
  'Ceftriaxone',
  'Cefpodoxime',
  'Cefdinir',
  'Azithromycin',
  'Zithromax',
  'Clarithromycin',
  'Erythromycin',
  'Ciprofloxacin',
  'Levofloxacin',
  'Ofloxacin',
  'Metronidazole',
  'Flagyl',
  'Tinidazole',
  'Doxycycline',
  'Tetracycline',
  'Minocycline',
  'Linezolid',
  'Vancomycin',
  'Aztreonam',
  'Meropenem',
  'Imipenem',
  'Ertapenem',
  'Colistin',
  'Fluconazole',
  'Itraconazole',
  'Voriconazole',
  'Ketoconazole',
  'Nystatin',
  'Amphotericin B',
  'Aciclovir',
  'Acyclovir',
  'Valacyclovir',
  'Famciclovir',
  'Oseltamivir',
  'Tamiflu',
  'Hydroxyzine',
  'Loratadine',
  'Cetirizine',
  'Levocetirizine',
  'Fexofenadine',
  'Montelukast',
  'Budesonide',
  'Fluticasone',
  'Beclomethasone',
  'Salbutamol',
  'Ventolin',
  'Ipratropium',
  'Tiotropium',
  'Formoterol',
  'Salmeterol',
  'Salmeterol-Fluticasone',
  'Fluticasone-Salmeterol',
  'Levosalbutamol',
  'Ambroxol',
  'Acetylcysteine',
  'Expectorant',
  'Pseudoephedrine',
  'Phenylephrine',
  'Phenobarbitone',
  'Diazepam',
  'Alprazolam',
  'Clonazepam',
  'Lorazepam',
  'Midazolam',
  'Zolpidem',
  'Zopiclone',
  'Eszopiclone',
  'Triazolam',
  'Buspirone',
  'Haloperidol',
  'Risperidone',
  'Olanzapine',
  'Quetiapine',
  'Aripiprazole',
  'Sertraline',
  'Fluoxetine',
  'Escitalopram',
  'Paroxetine',
  'Amitriptyline',
  'Nortriptyline',
  'Duloxetine',
  'Venlafaxine',
  'Bupropion',
  'Atomoxetine',
  'Methylphenidate',
  'Donepezil',
  'Memantine',
  'Rivastigmine',
  'Levodopa',
  'Carbidopa-Levodopa',
  'Pramipexole',
  'Ropinirole',
  'Selegiline',
  'Gabapentin',
  'Pregabalin',
  'Topiramate',
  'Valproate',
  'Lamotrigine',
  'Phenytoin',
  'Carbamazepine',
  'Oxcarbazepine',
  'Clobazam',
  'Sumatriptan',
  'Ergotamine',
  'Topical steroid',
  'Hydrocortisone',
  'Betamethasone',
  'Clobetasol',
  'Mometasone',
  'Fluticasone (topical)',
  'Tacrolimus (topical)',
  'Calamine lotion',
  'Permethrin',
  'Permethrin cream',
  'Antifungal cream',
  'Terbinafine',
  'Naftifine',
  'Miconazole',
  'Clotrimazole',
  'Silver sulfadiazine',
  'Retinoids (Isotretinoin)',
  'Isotretinoin',
  'Doxycycline (derm)',
  'Minoxidil',
  'Finasteride',
  'Spironolactone',
  'Ophthalmic antibiotic drops',
  'Chloramphenicol eye drops',
  'Ofloxacin eye drops',
  'Moxifloxacin eye drops',
  'Timolol eye drops',
  'Latanoprost',
  'Travoprost',
  'Brimonidine',
  'Ciprofloxacin ear drops',
  'Neomycin-polymyxin ear drops',
  'Acetic acid ear drops',
  'Oral rehydration salts',
  'IV fluids (Normal saline)',
  'Salbutamol inhaler',
  'Budesonide inhaler',
  'Fluticasone inhaler',
  'Montelukast chewable',
  'Insulin NPH',
  'Insulin Regular',
  'Insulin Detemir',
  'Insulin Degludec',
  'Thyroxine',
  'Levothyroxine',
  'Propylthiouracil',
  'Carbimazole',
  'Lovastatin',
  'Niacin',
  'Vitamin D3',
  'Cholecalciferol',
  'Calcitriol',
  'Calcium carbonate',
  'Calcium citrate',
  'Ferrous sulfate',
  'Folic acid',
  'Vitamin B12',
  'Multivitamin',
  'Iron tablets',
  'Oral contraceptive pill',
  'Levonorgestrel',
  'Ethinylestradiol',
  'Emergency contraceptive',
  'Mefenamic acid',
  'Ketorolac',
  'Indomethacin (oral)',
  'Diclofenac gel',
  'Capsaicin cream',
  'Gabapentin (neuropathic pain)',
  'Pregabalin (neuropathic pain)',
  'Botulinum toxin',
  'Colchicine',
  'Allopurinol',
  'Febuxostat',
  'Probenecid',
  'Hydroxychloroquine',
  'Chloroquine',
  'Azathioprine',
  'Mycophenolate mofetil',
  'Cyclosporine',
  'Tacrolimus (systemic)',
  'Sirolimus',
  'Rituximab',
  'Infliximab',
  'Adalimumab',
  'Etanercept',
  'Golimumab',
  'Secukinumab',
  'Ustekinumab',
  'Tofacitinib',
  'Baricitinib',
  'Apremilast',
  'Bisphosphonates (Alendronate)',
  'Alendronate',
  'Risedronate',
  'Ibandronate',
  'Denosumab',
  'Calcitonin',
  'Ergocalciferol',
  'Tamoxifen',
  'Letrozole',
  'Anastrozole',
  'Exemestane',
  'Leuprolide',
  'Goserelin',
  'Triptorelin',
  'Imatinib',
  'Dasatinib',
  'Nilotinib',
  'Erlotinib',
  'Gefitinib',
  'Sorafenib',
  'Sunitinib',
  'Temozolomide',
  'Cisplatin',
  'Carboplatin',
  'Paclitaxel',
  'Docetaxel',
  'Capecitabine',
  '5-Fluorouracil',
  'Gemcitabine',
  'Oxaliplatin',
  'Etoposide',
  'Doxorubicin',
  'Adriamycin',
  'Bleomycin',
  'Vincristine',
  'Vinblastine',
  'Tamoxifen (onc)',
  'Metoclopramide (GI)',
  'Mesalazine',
  'Sulfasalazine',
  'Azathioprine (GI)',
  'Budecort',
  'Mesalamine',
  'Rifaximin',
  'Loperamide',
  'Simethicone',
  'Orlistat',
  'Phentermine',
  'Lorcaserin',
  'Propranolol',
  'Atenolol (migraine prophylaxis)',
  'Timolol (ophthalmic)',
  'Calcium channel blocker',
  'Nifedipine',
  'Isosorbide mononitrate',
  'GTN patch',
  'Isosorbide dinitrate',
  'Digoxin',
  'Amiodarone',
  'Sotalol',
  'Flecainide',
  'Ivabradine',
  'Hydrochlorothiazide',
  'Chlorthalidone',
  'Indapamide',
  'Aminophylline',
  'Theophylline',
  'Zafirlukast',
  'Fluorouracil (topical)',
  'Imiquimod',
  'Hydroxyurea',
  'Olopatadine',
  'Ketotifen',
  'Rifampicin',
  'Isoniazid',
  'Pyrazinamide',
  'Ethambutol',
  'Streptomycin',
  'Propranolol (thyroid storm supportive)',
  'Prednisone',
  'Methylprednisolone',
  'Dexamethasone',
  'Hydrocortisone (IV)',
  'Prednisolone (oral)',
  'Triamcinolone',
  'Beclometasone (inhaled)',
  'Fluticasone (inhaled)',
  'Budesonide (inhaled)',
  'Levonorgestrel IUD',
  'Medroxyprogesterone',
  'Misoprostol',
  'Oxytocin',
  'Carboprost',
  'Ergometrine',
  'Tranexamic acid',
  'Misoprostol (GI/OB)',
  'Ketamine',
  'Propofol',
  'Fentanyl',
  'Remifentanil',
  'Morphine',
  'Buprenorphine',
  'Tramadol (opioid)',
  'Codeine phosphate',
  'Pramoxine',
  'Silver nitrate',
  'Polymyxin B',
  'Neomycin',
  'Bacitracin',
  'Mupirocin',
  'Fusidic acid',
  'Dicloxacillin',
  'Flucloxacillin',
  'Beta-lactamase inhibitors',
  'Cephalexin',
  'Cefadroxil',
  'Artemether-Lumefantrine',
  'Chloroquine phosphate',
  'Primaquine',
  'Mefloquine',
  'Hydroxychloroquine sulfate',
  'Oseltamivir phosphate',
  'Ribavirin',
  'Sofosbuvir',
  'Ledipasvir',
  'Simeprevir',
  'Velpatasvir',
  'Interferon alfa',
  'Ribavirin (HCV)',
  'Sitagliptin-metformin',
  'Metformin SR',
  'Glibenclamide (Glyburide)',
  'Repaglinide',
  'Nateglinide',
  'Acarbose',
  'Vildagliptin-metformin',
  'Insulin glulisine',
  'Insulin 30/70',
  'Insulin 70/30',
  'Empagliflozin-metformin',
  'Linagliptin',
  'Saxagliptin-metformin',
  'Hydroxytryptophan',
  'Levodopa-Carbidopa',
  'Selegiline (Parkinson\'s)',
  'Piracetam',
  'Citicoline',
  'Hyoscine butylbromide',
  'Drotaverine',
  'Domperidone (antiemetic)',
  'Ondansetron (antiemetic)',
  'Rifaximin (GI)',
  'Tadalafil',
  'Sildenafil',
  'Vardenafil',
  'Avanafil',
  'Finasteride (BPH)',
  'Tamsulosin',
  'Doxazosin',
  'Terazosin',
  'Silodosin',
  'Dutasteride',
  'Oxybutynin',
  'Solifenacin',
  'Darifenacin',
  'Trospium',
  'Bethanechol',
  'Mirabegron',
  'Bisacodyl',
  'Lactulose',
  'Polyethylene glycol',
  'Senna',
  'Promethazine (antiemetic)',
  'Prochlorperazine',
  'Metoclopramide (antiemetic)',
  'Linezolid (antibiotic)',
  'Rifaximin (antibiotic)',
  'Fosfomycin',
  'Nitrofurantoin',
  'Furazolidone',
  'Phenazopyridine',
  'Cefoperazone',
  'Cefotaxime',
  'Diclofenac sodium',
  'Diclofenac potassium',
  'Ketoprofen',
  'Flurbiprofen',
  'Ketorolac tromethamine',
  'Magnesium sulfate',
  'Calcium polystyrene sulfonate',
  'Sodium polystyrene sulfonate',
  'Polymyxin E (Colistin)',
  'Zonisamide',
  'Perampanel',
  'Ezogabine',
  'Levetiracetam',
  'Brivaracetam',
  'Stiripentol',
  'Rufinamide',
  'Vigabatrin',
  'Phenobarbital',
  'Pregabalin (neuropathic pain)',
  'Oxytocin (ob)',
  'Terbutaline',
  'Ritodrine',
  'Salbutamol (tablet)',
  'Hydrocortisone (topical)',
  'Mometasone furoate',
  'Beclomethasone (topical)',
  'Gentamicin (topical)',
  'Clotrimazole (vaginal)',
  'Metronidazole (vaginal)',
  'Fluconazole (vaginal)',
  'Silver sulfadiazine (topical)',
  'Neomycin (topical)',
  'Mupirocin (topical)'
].map(s => s.trim());

// Lowercase -> original case map for fast exact matching
export const EXTENDED_MEDICINE_MAP: Map<string, string> = new Map(
  EXTENDED_MEDICINE_NAMES.map((n) => [n.toLowerCase(), n])
);
